apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/sdnet: "true"
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: INIT_TOKUDB
          value: "1"
        - name: MYSQL_DATABASE
          value: cloud-crematory
        - name: MYSQL_ROOT_PASSWORD
          value: grc57lL91Al
        - name: MYSQL_USER
          value: root
        image: e0steven/percona5.7-tokudb-centos68
        imagePullPolicy: ""
        name: mysql-db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldata
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysqldata
        persistentVolumeClaim:
          claimName: mysqldata
status: {}
